name: deploy

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: deploy

    env:
      image_tag: vite-r3f

    steps:
      - name: checkout tagged branch
        uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Build Check
        run: |
          yarn install
          yarn run build